name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=onedark&show_icons=true&bg_color=00000000&hide_border=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&theme=onedark&show_icons=true&layout=compact&hide=html,css,cmake,php&size_weight=0.5&count_weight=0.5&langs_count=8&bg_color=00000000&hide_border=true
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate sandbox pin card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=sandbox&theme=onedeark&bg_color=00000000&hide_border=true&description_lines_count=3
          path: profile/pin-sandbox-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate charlene pin card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=charlene&bg_color=00000000&hide_border=true&description_lines_count=3
          path: profile/pin-charlene-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tp pin card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=tp&bg_color=00000000&hide_border=true&description_lines_count=3
          path: profile/pin-tp-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate skelly pin card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=skelly&bg_color=00000000&hide_border=true&description_lines_count=3
          path: profile/pin-skelly-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate dotfiles pin card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=dotfiles&bg_color=00000000&hide_border=true&description_lines_count=3
          path: profile/pin-dotfiles-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate scripts pin card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=scripts&bg_color=00000000&hide_border=true&description_lines_count=3
          path: profile/pin-scripts-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
